export const  data=[
    {
        Name:'The Complete Python Programming Course',
        image:'https://media.geeksforgeeks.org/wp-content/cdn-uploads/20210215160315/FREE-Python-Course-For-Beginners.png',
        Author:'Avinash Jain',
        actualprice:'1,499',
        price:'499',
        description:'Master Python by building 100 projects in 100 days. Learn data science, automation, build websites, games and apps!',
        rating:3,
        category:'programming language',
        reviews:'21,336',
    },
    {
        Name:'C++ Programming For Begineers',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTggnWOHditMP1qlVy0wFSYTamZTgs5c_emyg&usqp=CAU',
        Author:'Jason Fedin',
        actualprice:'1,999',
        price:'999',
        description:'C++ Programming will increase career options. Become a better dev in other languages by learning C++. Pointers explained.',
        rating:4.5,
        category:'programming language',
        reviews:'11,336',
    },
    {
        Name:'The Complete JavaScript Course 2022: From Zero to Expert!',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ4qe-TiNdb7kONl0a1C3a1R3H9TPWKSJeGg&usqp=CAU',
        Author:'Jonas schmedtmann',
        actualprice:'2,999',
        price:'999',
        description:'The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!',
        rating:3.5,
        category:'programming language',
        reviews:'12,336',
    },
    {
        Name:'Mastering Data Structures & Algorithms using C and C++',
        image:'https://ict.iitk.ac.in/wp-content/uploads/Data-Structure-through-C-2.jpg',
        Author:'Abdul Bari',
        actualprice:'1,999',
        price:'599',
        description:'Learn, Analyse and Implement Data Structure using C and C++. Learn Recursion and Sorting.',
        rating:4.7,
        category:'Data Structures & Algorithms',
        reviews:'22,933',
    },
    {
        Name:'Mastering Data Structures & Algorithms using Java',
        image:'https://1.bp.blogspot.com/-v9vxotekYmQ/W-0FYBDUi1I/AAAAAAAAEts/M_pH2lbqQ1Aaim-7qbp1l01sabf9l9htQCLcBGAs/s1600/java-datastructures-and-algorithms.png',
        Author:'Goran lochert',
        actualprice:'3,499',
        price:'599',
        description:'Learn about Arrays, Linked Lists, Trees, Hashtables, Stacks, Queues, Heaps, Sort algorithms and Search algorithms',
        rating:4.4,
        category:'Data Structures & Algorithms',
        reviews:'1,336',
    },
    {
        Name:'Mastering Data Structures & Algorithms using Python',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTghlM10huuSIRCJs34UGxJV93uDXL3-FOo1QnVNuIDguAFc46ue6gtTUxo2g603L7yq9Q&usqp=CAUhttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoC_TJzkC_4xY5wWByNrzq5PQPLv46igSBww&usqp=CAU',
        Author:'Elshad karimov',
        actualprice:'2,599',
        price:'599',
        description:'Data Structures and Algorithms from Zero to Hero and Crack Top Companies 100+ Interview questions (Python Coding)',
        rating:3.6,
        category:'Data Structures & Algorithms',
        reviews:'336',
    },
    {
        Name:'Master Course on Graph Algorithms',
        image:'https://www.codingninjas.com/blog/wp-content/uploads/2021/06/Blog-2021-06-04T140942.231.png',
        Author:'Elshad karimov',
        actualprice:'2,999',
        price:'599',
        description:'Data Structures and Algorithms from Zero to Hero and Crack Top Companies 100+ Interview questions (Python Coding)',
        rating:3.6,
        category:'Data Structures & Algorithms',
        reviews:'336',
    },
    {
        Name:'HTML Made Simple For Beginners',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoQcUBh2FX-xhWLzJFqejFYIoE3dpXdgPjwmxV40Y&s',
        Author:'Avinash Triphaty',
        actualprice:'2,999',
        price:'599',
        description:'Learn how to write easy to understand HTML code and create a basic one page website with an image ,audio and video.',
        rating:3.8,
        category:'Web Devlopement',
        reviews:'7,336',
    },
    {
        Name:'CSS Made Simple For Beginners',
        image:'https://repository-images.githubusercontent.com/200002869/f70b1800-8587-11ea-9ec4-2e5d785fb723',
        Author:'Avinash Triphaty',
        actualprice:'3,999',
        price:'599',
        description:'Learn CSS for the first time or brush up your CSS skills and dive in even deeper. EVERY web developer has to know CSS.',
        rating:3.8,
        category:'Web Devlopement',
        reviews:'3,336',
    },
    {
        Name:'React - The Complete Guide ',
        image:'https://hackr.io/blog/react-courses/thumbnail/large',
        Author:'Haris ali khan',
        actualprice:'1,299',
        price:'599',
        description:'Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!',
        rating:4.3,
        category:'Web Devlopement',
        reviews:'32,736',
    },
    {
        Name:'Node.js, Express, MongoDB & More ',
        image:'https://www.section.io/engineering-education/history-of-nodejs/nodejs-use-cases-cover-image.png',
        Author:'Haris ali khan',
        actualprice:'3,199',
        price:'599',
        description:'Master Node by building a real-world RESTful API and web app (with authentication, Node.js security, payments & more)',
        rating:4.5,
        category:'Web Devlopement',
        reviews:'9,036',
    },
    {
        Name:'The Complete 2022 Web Development Course',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl14eBWvd8MbFzNdCMZNhQc5eVLWvu9VvDoV3JEchAcgpmS0VUoUeoISF6Jb_7XbfizA8&usqp=CAU',
        Author:'Jason Fedin',
        actualprice:'6,999',
        price:'1,399',
        description:'The only course you need to become a full-stack web developer. Covers HTML5, CSS3, JS, ES6, Node, APIs, Mobile & more!',
        rating:3.2,
        category:'Web Devlopement',
        reviews:'2,896',
    },
    {
        Name:'React Native - The Practical Guide ',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIUDBwUQ4OeYOcuZ9MA4gFuJ4rc3LnWoR0pQ&usqp=CAU',
        Author:'Binod thapa',
        actualprice:'7,999',
        price:'1,499',
        description:'Use React Native and your React knowledge to build native iOS and Android Apps - incl. Push Notifications, Hooks, Redux',
        rating:4,
        category:'Mobile App Devlopement',
        reviews:'14,336',
    },
    {
        Name:'Learn Java the Easy Way: Build Desktop & Android Mobile Apps',
        image:'https://miro.medium.com/max/689/1*wSxeE-1tYe0e0uFJ1hJQRg.jpeg',
        Author:'Jonas schmedtmann',
        actualprice:'8,999',
        price:'1,099',
        description:'A Hands-On Introduction to Programming in Java on PC, Mac, Linux and Android Devices.',
        rating:4.1,
        category:'Mobile App Devlopement',
        reviews:'23,336',
    },
    {
        Name:'Complete Kotlin development masterclass 2022',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTRwNZb1y5s5CUIyVgXOCvuviP23tFGCPc1Q&usqp=CAU',
        Author:'catalin stefan',
        actualprice:'9,999',
        price:'1,999',
        description:'Master the fundamentals and advanced features of Kotlin development.',
        rating:4.2,
        category:'Mobile App Devlopement',
        reviews:'7,134',
    },
    {
        Name:'Flutter & Dart - The Complete Guide',
        image:'https://cdn-media-1.freecodecamp.org/images/MiAWLAfns7pPgptcHFFPe8UAwMhPTPp3WWgt',
        Author:'catalin stefan',
        actualprice:'9,999',
        price:'3,999',
        description:'Master the fundamentals and advanced features of Flutter development.',
        rating:4.2,
        category:'Mobile App Devlopement',
        reviews:'7,134',
    },
    {
        Name:'50 Projects In 50 Days - HTML, CSS & JavaScript',
        image:'https://miro.medium.com/max/1400/0*crN1sMRpNnApF9Pe.png',
        Author:'catalin stefan',
        actualprice:'8,999',
        price:'2,199',
        description:'Sharpen your skills by building 50 quick, unique & fun mini projects',
        rating:3.9,
        category:'Projects',
        reviews:'27,134',
    },

]